version: '3'
services:
  registry:
    image: descartesresearch/teastore-registry
    expose:
      - "8080"
    environment:
      SERVICE_PORT: "10000"
      HOST_NAME: "registry"
    ports:
      - "10000:8080"
  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
  persistence:
    image: descartesresearch/teastore-persistence
    expose:
      - "8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      # REGISTRY_PORT: "10000"
      DB_HOST: "db"
      DB_PORT: "3306"
      SERVICE_PORT: "1111"
    ports:
      - "1111:8080"
  auth:
    image: descartesresearch/teastore-auth
    expose:
      - "8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
      SERVICE_PORT: "2222"
    ports:
      - "2222:8080"
  image:
    image: descartesresearch/teastore-image
    expose:
      - "8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
      SERVICE_PORT: "4444"
    ports:
      - "4444:8080"
  recommender:
    image: descartesresearch/teastore-recommender
    expose:
      - "8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
      SERVICE_PORT: "3333"
    ports:
      - "3333:8080"
  webui:
    image: descartesresearch/teastore-webui
    expose:
      - "8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
      # REGISTRY_PORT: "10000"
      DB_HOST: "db"
      DB_PORT: "3306"
    ports:
      - "8080:8080"